# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='options_num',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='question',
            name='subject_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
