# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-15 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210514_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct',
            new_name='correct_num',
        ),
    ]
