# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_choice_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default='True'),
        ),
    ]
